pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests -Denforcer.skip=true clean package'
            }
        }
        stage("Archive") {
		    steps {
			    archiveArtifacts artifacts: 'target/*.jar', onlyIfSuccessful: true
			}
		}
    }
}
